name: product-api
services:
  db:
    image: postgres:12.22
    container_name: product-api-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=product-api
    ports:
      - '5432:5432'
    volumes:
      - ./.pgdata:/var/lib/postgresql/data